Ext.define('AM.view.user.List', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.userlist',

    title: 'All Users',
    store: 'Users',


    initComponent: function () {

        this.columns = [
            { header: 'Master Name', dataIndex: 'MasterName', width: 200, hidden: false },
            { header: 'Description', dataIndex: 'Description', flex: 1, hidden: false},
            /*{ header: 'View Portfolio', dataIndex: 'ViewPortfolio', flex: 1, hidden: true},
            { header: 'App Id From Source', dataIndex: 'AppIdFromSource', flex: 1, hidden: true },
            { header: 'Alias Names', dataIndex: 'AliasNames', flex: 1, hidden: true },
            { header: 'Modules', dataIndex: 'Modules', flex: 1, hidden: true },
            { header: 'Components', dataIndex: 'Components', flex: 1, hidden: true },
            { header: 'Vendor', dataIndex: 'Vendor', flex: 1, hidden: false },
            { header: 'SKU', dataIndex: 'SKU', flex: 1, hidden: true },
            { header: 'Portfolio', dataIndex: 'Portfolio', flex: 1, hidden: true },
            { header: 'AppSuite', dataIndex: 'AppSuite', flex: 1, hidden: true },
            { header: 'Version', dataIndex: 'Version', flex: 1, hidden: true },
            { header: 'Types', dataIndex: 'Types', flex: 1, hidden: true },
            { header: 'Url', dataIndex: 'Url', flex: 1, hidden: true },
            { header: 'Vendor Product Name', dataIndex: 'VendorProductName', flex: 1, hidden: true },
            { header: 'Common Product Name', dataIndex: 'CommonProductName', flex: 1, hidden: true },
            { header: 'Programmes', dataIndex: 'Programmes', flex: 1, hidden: true },
            { header: 'Subprogrammes', dataIndex: 'Subprogrammes', flex: 1, hidden: true },
            { header: 'PpiBoards', dataIndex: 'PpiBoards', flex: 1, hidden: true },
            { header: 'L1 Business Capabilities', dataIndex: 'L1BusinessCapabilities', flex: 1, hidden: true },
            { header: 'L2 Business Capabilities', dataIndex: 'L2BusinessCapabilities', flex: 1, hidden: true },
            { header: 'L1EDMs', dataIndex: 'L1EDMs', flex: 1, hidden: true },
            { header: 'L2EDMs', dataIndex: 'L2EDMs', flex: 1, hidden: true },
            { header: 'Assets', dataIndex: 'Assets', flex: 1, hidden: true },
            { header: 'Business Functions', dataIndex: 'BusinessFunctions', flex: 1, hidden: true },
            { header: 'VAFStages', dataIndex: 'VAFStages', flex: 1, hidden: true },
            { header: 'BusinessOwners', dataIndex: 'BusinessOwners', flex: 1, hidden: true },
            { header: 'TechnicalOwners', dataIndex: 'TechnicalOwners', flex: 1, hidden: true },
            { header: 'Age_str', dataIndex: 'Age_str', flex: 1, hidden: true },
            { header: 'NumberOfLicenses_str', dataIndex: 'NumberOfLicenses_str', flex: 1, hidden: true },
            { header: 'NoOfUsers_str', dataIndex: 'NoOfUsers_str', flex: 1, hidden: true },
            { header: 'InfraTypeOfApp', dataIndex: 'InfraTypeOfApp', flex: 1, hidden: true },
            { header: 'InfraPresentationType', dataIndex: 'InfraPresentationType', flex: 1, hidden: true },
            { header: 'InfraDBMS', dataIndex: 'InfraDBMS', flex: 1, hidden: true },
            { header: 'InfraOS', dataIndex: 'InfraOS', flex: 1, hidden: true },
            { header: 'InfraHostedLocation', dataIndex: 'InfraHostedLocation', flex: 1, hidden: true },
            { header: 'InfraCustomAppTechnology', dataIndex: 'InfraCustomAppTechnology', flex: 1, hidden: true },
            { header: 'InfraPresentationType', dataIndex: 'InfraPresentationType', flex: 1, hidden: true },
            { header: 'InfraPackagedCustomBoth', dataIndex: 'InfraPackagedCustomBoth', flex: 1, hidden: true },
            { header: 'InfraIsApplicationArchitecture', dataIndex: 'InfraIsApplicationArchitecture', flex: 1, hidden: true },
            { header: 'InfraAccessMethod', dataIndex: 'InfraAccessMethod', flex: 1, hidden: true },
            { header: 'InfraDeliveryMethod', dataIndex: 'InfraDeliveryMethod', flex: 1, hidden: true },
            { header: 'InfraDeployedFromWhere', dataIndex: 'InfraDeployedFromWhere', flex: 1, hidden: true },
            { header: 'InfraUsersWhere', dataIndex: 'InfraUsersWhere', flex: 1, hidden: true },
            { header: 'InfraPresentationType', dataIndex: 'InfraPresentationType', flex: 1, hidden: true },
            { header: 'InfraPackagingVersion', dataIndex: 'InfraPackagingVersion', flex: 1, hidden: true },
            { header: 'InfraPackageName', dataIndex: 'InfraPackageName', flex: 1, hidden: true },
            { header: 'InfraUpdateFrequency', dataIndex: 'InfraUpdateFrequency', flex: 1, hidden: true },
            { header: 'InfraUserGroup', dataIndex: 'InfraUserGroup', flex: 1, hidden: true },
            { header: 'InfraIsCoreApp', dataIndex: 'InfraIsCoreApp', flex: 1, hidden: true },
            { header: 'ServiceLevelAgreement', dataIndex: 'ServiceLevelAgreement', flex: 1, hidden: true },
            { header: 'Support1stLevelSupport', dataIndex: 'Support1stLevelSupport', flex: 1, hidden: true },
            { header: 'Support2ndLevelSupport', dataIndex: 'Support2ndLevelSupport', flex: 1, hidden: true },
            { header: 'Support3rdLevelSupport', dataIndex: 'Support3rdLevelSupport', flex: 1, hidden: true },
            { header: 'Support4thLevelSupport', dataIndex: 'Support4thLevelSupport', flex: 1, hidden: true },
            { header: 'Support5thLevelSupport', dataIndex: 'Support5thLevelSupport', flex: 1, hidden: true },
            { header: 'InfraBlueprintApplicationTier', dataIndex: 'InfraBlueprintApplicationTier', flex: 1, hidden: true },
            { header: 'InfraBlueprintIsHostedOrLocal', dataIndex: 'InfraBlueprintIsHostedOrLocal', flex: 1, hidden: true },
            { header: 'InfraBlueprintDataCenter', dataIndex: 'InfraBlueprintDataCenter', flex: 1, hidden: true },
            { header: 'InfraBlueprintClustered', dataIndex: 'InfraBlueprintDataCenter', flex: 1, hidden: true },
            { header: 'InfraBlueprintLocalAsset', dataIndex: 'InfraBlueprintLocalAsset', flex: 1, hidden: true },
            { header: 'InfraBlueprintCitrixFarm', dataIndex: 'InfraBlueprintCitrixFarm', flex: 1, hidden: true },
            { header: 'InfraBlueprintExternal', dataIndex: 'InfraBlueprintExternal', flex: 1, hidden: true },
            { header: 'InfraBlueprintDateCentreGeography', dataIndex: 'InfraBlueprintDateCentreGeography', flex: 1, hidden: true },
            { header: 'InfraBlueprintHostedCitrix', dataIndex: 'InfraBlueprintHostedCitrix', flex: 1, hidden: true },
            { header: 'InfraBlueprintNumberOfVersions', dataIndex: 'InfraBlueprintNumberOfVersions', flex: 1, hidden: true },
            { header: 'InfraBlueprintDisasterRecovery', dataIndex: 'InfraBlueprintDisasterRecovery', flex: 1, hidden: true },
            { header: 'InfraBlueprintAppVersion', dataIndex: 'InfraBlueprintAppVersion', flex: 1, hidden: true },
            { header: 'InfraBlueprintServerName', dataIndex: 'InfraBlueprintServerName', flex: 1, hidden: true },
            { header: 'InfraBlueprintServerNameDBMS', dataIndex: 'InfraBlueprintServerNameDBMS', flex: 1, hidden: true },
            { header: 'InfraBlueprintOSServer', dataIndex: 'InfraBlueprintOSServer', flex: 1, hidden: true },
            { header: 'InfraBlueprintOSDBMS', dataIndex: 'InfraBlueprintOSDBMS', flex: 1, hidden: true },
            { header: 'InfraBlueprintRichClientThinClient', dataIndex: 'InfraBlueprintRichClientThinClient', flex: 1, hidden: true },
            { header: 'InfraBlueprintDataStoredonShareDrive', dataIndex: 'InfraBlueprintDataStoredonShareDrive', flex: 1, hidden: true },
            { header: 'InfraBlueprintLDAP', dataIndex: 'InfraBlueprintLDAP', flex: 1, hidden: true },
            { header: 'InfraBlueprintEncryption', dataIndex: 'InfraBlueprintEncryption', flex: 1, hidden: true },
            { header: 'InfraBlueprintMesgFormat', dataIndex: 'InfraBlueprintMesgFormat', flex: 1, hidden: true },
            { header: 'InfraBlueprintWebService', dataIndex: 'InfraBlueprintWebService', flex: 1, hidden: true },
            { header: 'InfraBlueprintAppServer', dataIndex: 'InfraBlueprintAppServer', flex: 1, hidden: true },
            { header: 'InfraBlueprintWebServer', dataIndex: 'InfraBlueprintWebServer', flex: 1, hidden: true },
            { header: 'InfraBlueprintSolutionArchitect', dataIndex: 'InfraBlueprintSolutionArchitect', flex: 1, hidden: true },
            { header: 'InfraBlueprintCasewiseCategory', dataIndex: 'InfraBlueprintCasewiseCategory', flex: 1, hidden: true },
            { header: 'PetrotechToolkitsFunnel', dataIndex: 'PetrotechToolkitsFunnel', flex: 1, hidden: true },
            { header: 'PetrotechToolkitsProcess', dataIndex: 'PetrotechToolkitsProcess', flex: 1, hidden: true },
            { header: 'PetrotechToolkitsOwner', dataIndex: 'PetrotechToolkitsOwner', flex: 1, hidden: true },
            { header: 'PetrotechToolkitsAll', dataIndex: 'PetrotechToolkitsAll', flex: 1, hidden: true }*/
        ];

        this.callParent(arguments);
    }
});